### ISSUE TITLE
Toolbar button gets scroll bar on Linux Mint 17 Cinnamon

### ISSUE THREAD

**Issue by blaabjerg** [olsh/Feedly-Notifier-Firefox#102]
When adding the extension to a fresh installation of Firefox 32.0.3 on Linux Mint, the status bar icon gets a scroll bar whenever there are unread feeds. It appears to be a pixel too high. Here's a screenshot:

![screenshot from 2014-09-25 18 13 21](https://cloud.githubusercontent.com/assets/1731658/4408231/7e3602a2-44d1-11e4-8588-27c4cf2fec4e.png)

None of the other extensions I use (Hola, Ghostery, ABP, Undo Closed Tab Button, Pocket, etc) have this problem.

I was unable to reproduce the issue on my Ubuntu 14.04 box running Gnome 3, so it may be specific to Mint or Cinnamon somehow.

I downloaded a vanilla Firefox .tar.bz2 to see if it's caused by any unofficial modifications by Linux Mint, but the bug appeared in the vanilla build as well.

edit: I just tested in Xfce on the Linux Mint box and I was unable to reproduce the issue, so it appears to be specific to Cinnamon.

**Comment by olsh** [comment]
Please try [the new version](https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0). I hope it'll solve the problem.

Feel fre to reopen the issue.
