### ISSUE TITLE
Notification sometimes doesn't disappear

### ISSUE THREAD

**Issue by Inoki** [olsh/Feedly-Notifier-Firefox#104]
Often the notification after showing the count and saying "You have many new feeds" doesn't disappear and I suspect it might be connected to the sound notification, but am not sure.

I checked if there are some settings for that but couldn't find any.

I'm on Ubuntu 14.04 x64 with FF latest.

**Comment by olsh** [comment]
Is the problem still exists? Have you figured out what is the cause of the bug?
I can't reproduce it on Windows.

**Comment by Inoki** [comment]
Unfortunately I can't test it again since I'm on new hardware running Windows 8.1. The response got to me a tad late.
