### ISSUE TITLE
Icon Doesn't show up

### ISSUE THREAD

**Issue by Garshasb** [olsh/Feedly-Notifier-Firefox#106]
Hi
I'm using Feedly Notifier for a long time now. It worked up to firefox 29 and then stopped working when firefox lunched it's new UI...I then found out it's been updated...I updated it and it worked properly with firefox 33 but then after updating to 34 it stopped working...
I use firefox 34 on Windows 8.1

**Comment by olsh** [comment]
FF 36 was released. [Here is the new version of the addon](https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0).
Feel free to reopen the issue if the new version does not resolve the problem.
