### ISSUE TITLE
Notifier icon does not fit in

### ISSUE THREAD

**Issue by tomassvoboda** [olsh/Feedly-Notifier-Firefox#107]
![Feedly Notifier icon](https://cloud.githubusercontent.com/assets/3251053/5697294/a2c1fb7e-99ec-11e4-99b9-59ea21772328.png)
Feedly Notifier icon looks like it is on a button? I would like it to be only the green logo without the light rectangle around. It looks the same with the current theme as well as with the "devedition" theme.

I am on OS X Yosemite with Firefox 35 beta. 

Also when I hover over the icon with cursor, for example in Linux, the area highlighted is larger then for the rest of the icons on the toolbar.

**Comment by olsh** [comment]
Hello @tomassvoboda , thank you for the report.
All these problems will be fixed when [the new API](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_toggle#badge) will be released. (Firefox 36).

**Comment by tomassvoboda** [comment]
Oh, sorry for another issue if you are aware of it already. I am new to Firefox. Thanks for your work.

**Comment by olsh** [comment]
No problem at all.
It's good that you've reported about it.

**Comment by olsh** [comment]
You can download the fixed version [here](https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0).
Feel free to reopen the issue if bug still exists.
