### ISSUE TITLE
Use Austrialis ToggleButton and Panel for Feedly button

### ISSUE THREAD

**Issue by JoshTumath** [olsh/Feedly-Notifier-Firefox#109]
It would be good if the add-on was updated to use the newer Austrialis style of button with an associated panel.

https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_toggle#Badged_buttons

**Comment by olsh** [comment]
Thank you for the suggestion.
There is already a branch for this feature.
https://github.com/olsh/Feedly-Notifier-Firefox/tree/new_icon_api

And you can try [this build](https://github.com/olsh/Feedly-Notifier-Firefox/issues/92#issuecomment-63876382) which uses the API.

**Comment by JoshTumath** [comment]
Oh sorry. Wasn't aware there was a branch for it. Just tried the build and it's working great.

**Comment by olsh** [comment]
https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0
The version has been published and will be approved shortly, I hope.
