### ISSUE TITLE
Unread news Counter is missing

### ISSUE THREAD

**Issue by paland3** [olsh/Feedly-Notifier-Firefox#118]
Firefox 38.0.5,
Feedly Notifier 2.10.5

The option is ticked, the counter is not shown. Tried to reinstall, disable, no change.

**Comment by olsh** [comment]
@paland3 have you tried to Logout/Login?
Can you see news in the popup?

**Comment by paland3** [comment]
Thanks for the fast reply. I logged  out as you suggested, and logged in again. However, the problem is still there.

**Comment by olsh** [comment]
Could you please [create a new FF profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_creating-a-profile)? Just for test.

**Comment by paland3** [comment]
Hi, thanks again. After creating a new profile, the counter is back (using the new profile.) Does that mean the problem is local, some messed up cache of my profile?

**Comment by olsh** [comment]
Yes, I believe that problem is in you profile or it can be a conflict with one of your other addons.
Could you send me the list of installed addons? I'll try to reproduce the bug.

**Comment by paland3** [comment]
ok
Is it ok like this? These are the enabled ones.
![addondebug](https://cloud.githubusercontent.com/assets/7983561/8209670/96c1d662-150e-11e5-88b4-c3cbbac6a1f3.PNG)

**Comment by olsh** [comment]
Yes, it's OK, thank you, i'll test it.

**Comment by olsh** [comment]
I was unable to reproduce the bug.
Stupid question, have you tried to search the addon button in [the customize mode](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars)? 
Maybe the icon that in the toolbar actually is not Feedly Notifier button, but the original feedly addon?

**Comment by paland3** [comment]
Dear olsh,

yes I am pretty sure it was the Notifier button, since it opened the popup.
However, this one is fixed now, I don't know how. Here is what I have done, maybe it helps:
-use it without the number for a while
-uninstall extension
-refresh firefox (was slow anyway)
-reinstall extension

Now it is there. Thanks for the help, sorry that I could not be specific enough.
