### ISSUE TITLE
Icon counter always shows a 1 even though no new feeds

### ISSUE THREAD

**Issue by kizer8** [olsh/Feedly-Notifier-Firefox#119]
I am running Firefox v38.0.5 with the Feedly Notifier v2.10.6.  My icon counter always shows a 1 even though there are no feeds.  See attached screenshot.  Anyway to reset permanently and stop it from showing 1 even though there are no new feeds?

![counter](https://cloud.githubusercontent.com/assets/5338575/8396625/eb0b6478-1d73-11e5-8ccb-77859abb90ea.jpg)

**Comment by olsh** [comment]
Could you please check it in the Chrome version?

**Comment by kizer8** [comment]
I don't use chrome... I use firefox.

**Comment by kizer8** [comment]
I tested in chrome also and was getting a 1 counter.. I found the issue, I had a feed that was stuck on 1 and didn't see it.. I removed it and readded it and now am fine.  Sorry for the bother.
