### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by edmt** [olsh/Feedly-Notifier-Firefox#123]
Hi, I have just translated a few sentences to Spanish (in POEditor) because I really like this project. Please let me know if there is anything in which I could help you.

Great work!

**Comment by olsh** [comment]
Hi @edmt, thank you for the translation. :+1:  I'll merge it and public the new version today.
Well, the project is needed in Japanese translation, if you know someone who can do that, please let me know. :)

**Comment by edmt** [comment]
Hi. Well, the good news is that now I'm using the new version in spanish, thanks a lot! The bad news is that I don't know nobody who can help with the japanese translation.

I'm closing this issue. Thank you!
