### ISSUE TITLE
Unresponsive Script Warning

### ISSUE THREAD

**Issue by RickUK** [olsh/Feedly-Notifier-Firefox#124]
Hi,
I have been having a problem and I cannot figure out what the cause of it is.
I keep getting a warning/error message and trying to use Feedly is really frustrating as the Browser takes a very long time to do anything when I try to add a new Feed.
It just seems to freeze up when I add a new Feed,and the only way to get things going,all be it...very slowly,is to left click on a blank part of the page,and then the mouse timer/cursor appears.I then have to click again,and I then get a message at the very top (Blue strip) of the browser saying it is Unresponsive.
If I wait long enough,eventually it completes itself,but, if I once again, click on a blank part of the page a few times,I get a box appear saying that the script has become unresponsive...do I want to continue/debug it/close it?
It does not seem to matter whether I continue,or close it...it,once again,it just takes a very long time to complete the action of adding a new Feed,and/or...once again,I end up having to click a blank part of the page a few times, to make the box go away,and have the needed,wished for action of adding a new Feed actually complete itself!
I know there are a few issues concerning a few Firefox Addons...and I am not running any of them.
I have clicked the option to debug the script,but I am not a "Coder"...and I do not understand what it is that the Debugger program is trying to let me know!
I have attached 2 screen shots:One is showing the message warning box that appears,and the other one is a screenshot of what the debugger shows when I click it.
I really like Feedly,and the features it has and really like the interface,but this issue is almost making using this program impractical,which is a shame indeed, as I have spent some time getting used to using it,and have built up a large list of RSS feeds.
I know I can import the feed(s) into another RSS program,but I would really prefer to continue using your program.
I have a feeling that this issue maybe due to Firefox browser,and not Feedly,but I am at a loss as to how to make both programs work nicely together.
I am running the latest version of Firefox.
I would appreciate any help you may be able to give concerning this really frustrating problem.

Thanks

Rick

![unresponsive script warning](https://cloud.githubusercontent.com/assets/14075942/9608875/771b354c-50c8-11e5-9be4-1242457ea0c9.JPG)
![debugger](https://cloud.githubusercontent.com/assets/14075942/9608874/77139f08-50c8-11e5-8d90-f23a188bf558.JPG)

**Comment by olsh** [comment]
Sorry, but the firefox addon is an unofficial extension.
You should send the report to Feedly directly.
https://feedly.uservoice.com/

**Comment by RickUK** [comment]
Ok...Thanks for responding to my post concerning the problem I am having.
I was not sure where to go for help...sorry to have posted in the wrong place!
I will contact them via the link you have kindly provided.
