### ISSUE TITLE
Проблема с авторизацией

### ISSUE THREAD

**Issue by Kzlv** [olsh/Feedly-Notifier-Firefox#126]
После нажатия на серую иконку расширения на панели инструментов, а затем на зеленую кнопку "Вход" появляется отдельная вкладка авторизации (на весь экран):
"Sign in to personalize your feedly and access it from everywhere
- Continue with Google
- Continue with Facebook..."

При попытке войти или через Google, или через Facebook после некоторого ожидания (а в это время происходит "Ожидание ответа от feedly.com..." "Соединение с localhost...") появляется сообщение
"Время ожидания ответа от сервера localhost истекло".

В результате в Feedly вход не выполняется (в Google или в Facebook вход выполняется).

Вход на сайт feedly.com не через расширение Feedly Notifier происходит без проблем (появляется не отдельная вкладка на весь экран, а всплывающее окошко авторизации).

Firefox 41.0.2
Feedly Notifier 2.10.8

**Comment by olsh** [comment]
Случайно не установлен какой-нибудь вебсервер локально? Apache?
Используется ли прокси?
Какая OS?
Попробуйте, просто для теста залогиниться с помощью [расширения для chrome](https://chrome.google.com/webstore/detail/feedly-notifier/egikgfbhipinieabdmcpigejkaomgjgb).

**Comment by Kzlv** [comment]
Установлен Handycache.
Прокси используется. 
Windows 7 SP1.
В Chrome все нормально (прокси тоже используется).

**Comment by olsh** [comment]
Попробуйте отключить прокси в ФФ, для теста.
А так же добавить в настройках прокси в ФФ в исключения *localhost* и *127.0.0.1*

**Comment by Kzlv** [comment]
localhost и 127.0.0.1 в исключениях есть и были.
При отключенном прокси (при режимах "Без прокси" или "Автоматически определять настройки прокси...") ситуация аналогичная.

**Comment by olsh** [comment]
Попробуйте для теста [создать новый профиль ФФ](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_creating-a-profile).
Возможно тогда что конфликт с каким-либо расширением.

**Comment by Kzlv** [comment]
При всех отключенных других расширениях ситуация такая же.

**Comment by olsh** [comment]
Со старым профилем или новый создавали?
Расширения вносят настройки в БД ФФ, если тестировали со старым, попробуйте создать новый, потом удалите.

**Comment by Kzlv** [comment]
Предыдущее мое сообщение касается старого профиля.

Создал новый профиль. Авторизовался. Все работает. В настройках прокси нового профиля по умолчанию отмечено "Использовать системные настройки..."

Установил такие же настройки прокси "Использовать системные..." на старом профиле. Заработало.
Переключил настройки прокси в старом профиле на "Ручная настройка..."
Работает.

**Comment by Kzlv** [comment]
Спасибо за подсказку.
Сам не додумался.

**Comment by olsh** [comment]
Пожалуйста, странный баг, непонятно где.
Если вдруг заметите какие-то детали, дайте знать.
Можете закрыть Issue если все работает.

**Comment by Kzlv** [comment]
Ок

**Comment by olsh** [comment]
Изменил URL для авторизации, теперь проблемы в принципе не должно возникать. Будет в версии 2.10.9.
