### ISSUE TITLE
Feedly popup sometimes blank

### ISSUE THREAD

**Issue by dorugeber** [olsh/Feedly-Notifier-Firefox#128]
[I will endeavour to take a screenshot next time this happens!]

Occasionally, the Feedly popup is entirely blank (even the website link and the top buttons are not displayed).  This then persists until Firefox is closed.

**Comment by olsh** [comment]
@dorugeber thank you for the reporting.
Related to https://github.com/olsh/Feedly-Notifier-Firefox/issues/110

**Comment by dorugeber** [comment]
Whoops, sorry, definitely a duplicate.
