### ISSUE TITLE
Alternative to Show Counter

### ISSUE THREAD

**Issue by Ghosting-X** [olsh/Feedly-Notifier-Firefox#129]
Is it possible for there to be another option that changes the icon to grey when when there is nothing new, then green when there is? "Show Counter" is currently mandatory if you just want to glance at the icon to see if there is anything new.

I know right now that the grey icon is being used for when your not logged in, but maybe that could be changed to something else. Seems every other add-on is using gray to show that there is nothing new, which is throwing me off because Feedly Notifier is constantly lit up.

**Comment by olsh** [comment]
@Ghosting-X 
Thank you for the suggestion, I'll implement it in the next version.
