### ISSUE TITLE
Notifier window pop-ups twice when toolbar icon is clicked

### ISSUE THREAD

**Issue by malibuzios** [olsh/Feedly-Notifier-Firefox#130]
I'm using `2.10.12` on Firefox 45.0.1 x64, Windows 10 x64.
The skin I'm using is called "Mac OSX Light".

I have many other add-ons installed. I'm willing to investigate this further if this is related to any one of them:

![feedlynotifierpopupstwice](https://cloud.githubusercontent.com/assets/17719551/14319429/d5845a80-fc19-11e5-97c6-02ca460f7fa8.gif)

This happens consistently and have been this way for more than a year now, I believe..

**Comment by olsh** [comment]
@malibuzios
Thank you for the reporting.

**Comment by malibuzios** [comment]
Thanks. I disabled all extensions and reverted back to the default theme and it also kept happening.
