### ISSUE TITLE
Allow shorter update periods

### ISSUE THREAD

**Issue by MikkCZ** [olsh/Feedly-Notifier-Firefox#132]
IMO 10 minutes are way too safe. Couldn't be e.g. 5 or 2 minutes allowed minimum?

**Comment by olsh** [comment]
@MikkCZ 
Thanks for the feedback.
Sadly, I can't make the update interval shorter than 10 minutes.
It's a part of an agreement with Feedly team.

**Comment by MikkCZ** [comment]
Interesting as I have also tested Feedly Notifier Plus before, which has default interval set within seconds.

**Comment by olsh** [comment]
Well, I'm not a dev of FN Plus, so, I don't know if the addon uses the official Feedly API or what kind of agreements they have with Feedly team.

Anyway, RSS is not about instant messages.

**Comment by olsh** [comment]
https://github.com/olsh/Feedly-Notifier-Safari/issues/2
