### ISSUE TITLE
Add-ons Manager icon missing

### ISSUE THREAD

**Issue by Imold** [olsh/Feedly-Notifier-Firefox#133]
Line 10 of package.json "data/images/icon48.png" should be "resource://jid1-bojn8b0im7kh2w-at-jetpack/data/images/icon48.png"

**Comment by olsh** [comment]
Closed in https://github.com/olsh/Feedly-Notifier-Firefox/commit/1113d45518720517a32b8915061b536dd7438a38

Thank you! :+1:
