### ISSUE TITLE
Button not showing up

### ISSUE THREAD

**Issue by Brawl345** [olsh/Feedly-Notifier-Firefox#92]
Hello,
the feedly button doesn't show up. It worked earlier, but now the button isn't there and notifications also don't work. I checked the customize menu, but the icon isn't there :(
I'm on Firefox 31 on Ubuntu 14.04 x64.

**Comment by olsh** [comment]
[The new version](https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0) has been released.
I hope it'll fixes all these icon related problems.

Feel free to reopen the issue.
