### ISSUE TITLE
Incompatibility with toolbars not registered with CustomizableUI (The Fox, Only Better add-on)

### ISSUE THREAD

**Issue by Quicksaver** [olsh/Feedly-Notifier-Firefox#97]
(Sorry about the double post, I hit the submit button by accident).

You can find the original report of the issue at https://github.com/Quicksaver/The-Fox--Only-Better/issues/65. In short, if both Feedly Notifier and [The Fox, Only Better](https://addons.mozilla.org/firefox/addon/the-fox-only-better/) are enabled, and the default theme is not enabled (any persona for instance, there are a few links at the bottom of that thread), the Feedly Notifier button will not appear after a browser restart. I have no idea why this only happens with a non-default theme enabled though.

On one hand, this may be related to #92, and I see there's some progress being done on the new API, so hopefully you can use it soon.

But mostly, I believe this is because in https://github.com/Rob--W/toolbarwidget-jplib/blob/master/lib/toolbarwidget.js#L108 the script searches the currentSet of all toolbar nodes (which is just a shim that uses the mechanisms inside the CustomizableUI module), without discriminating if those nodes are actually registered with the CustomizableUI module or not. In the case of my add-on, it adds a couple of toolbar nodes but those aren't actual toolbars (they are just toolbar nodes to make sure they respond properly to mouse events when in the top chrome), so Feedly Notifier fails to initialize because CUI throws an error since it can't find those toolbars in its data.

The solution is really simple, just add a small check in that loop, something like ```if(!toolbar.id || !CustomizableUI.getAreaType(toolbar.id)) continue;```. I'm not sure if I'm able to fix this within my add-on, as I don't want to register those toolbar nodes with CUI, it would bring many other problems as they're not supposed to be customized, or even taken into account for anything.

**Comment by olsh** [comment]
[The new version](https://addons.mozilla.org/en-US/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0) has been released.
I hope it'll fixes all these icon related problems.

Feel free to reopen the issue.
